### ISSUE TITLE
Panel Name not loading from cookie

### ISSUE THREAD

**Issue by EternalFlower** [EternalFlower/PSO2-Affix-Simulator#15]
When you rename the panel, it does not save the name when you save the panel and load it from the cookie or share the link.

**Comment by JimmyS24** [comment]
Most likely going to ignore sharing the name from the link since it would involves adding another params to the url but from cookie, we can used the name as the panel name.

**Comment by EternalFlower** [comment]
The work require to make the modification in the legacy cookie maker code will not justify the benefit.
